### ISSUE TITLE
check-tests fails on the CI with Prepend_dir and Update_ids 

### ISSUE THREAD

**Issue by bheemreddy181** [testomatio/check-tests#131]
Trace below- 

```
Generating script.
Script contents:
TESTOMATIO_PREPEND_DIR="Cash Money" TESTOMATIO=* npx check-tests@latest Playwright "**/*{.,_}{test,spec,cy}.ts" --typescript  --purge --no-detached --keep-structure --update-ids --sync --create
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /usr/local/azuredevopsagent/_work/_temp/9f550b77-aa0e-4b26-89b7-9feeed724d36.sh
 🤩 Tests checker by Testomat.io v0.8.19
Error: ENOENT: no such file or directory, open '/usr/local/azuredevopsagent/_work/1/s/tests/Capo.UI.Testing/Cash Money/tests/acquisition/loan-application.spec.ts'
Error: ENOENT: no such file or directory, open '/usr/local/azuredevopsagent/_work/1/s/tests/Capo.UI.Testing/Cash Money/tests/acquisition/loan-application.spec.ts'
    at Object.openSync (node:fs:589:3)
    at Object.readFileSync (node:fs:457:35)
    at cleanIdsCommon (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/src/updateIds/updateIds.js:121:26)
    at cleanIds (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/src/updateIds/index.js:11:10)
    at Command.<anonymous> (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/bin/check.js:89:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
##[error]Bash exited with code '1'.
Finishing: Upload Playwright tests

```

**Comment by bheemreddy181** [comment]
Same issue even without update_ids Generating script.


```
Script contents:
TESTOMATIO_PREPEND_DIR="Cash Money (CM)" TESTOMATIO=tstmt_cCVPfdQxiE4mWI9MMErGLXG4MX_pr9Xt6Q1692551415 npx check-tests@latest Playwright "**/*{.,_}{test,spec,cy}.ts" --typescript  --purge
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /usr/local/azuredevopsagent/_work/_temp/642c7dcd-6bba-485d-99f3-fae9af33b1eb.sh
 🤩 Tests checker by Testomat.io v0.8.19
Error: ENOENT: no such file or directory, open '/usr/local/azuredevopsagent/_work/1/s/tests/Capo.UI.Testing/Cash Money (CM)/tests/acquisition/loan-application.spec.ts'
Error: ENOENT: no such file or directory, open '/usr/local/azuredevopsagent/_work/1/s/tests/Capo.UI.Testing/Cash Money (CM)/tests/acquisition/loan-application.spec.ts'
    at Object.openSync (node:fs:589:3)
    at Object.readFileSync (node:fs:457:35)
    at cleanIdsCommon (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/src/updateIds/updateIds.js:121:26)
    at cleanIds (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/src/updateIds/index.js:11:10)
    at Command.<anonymous> (/home/azureagent/.npm/_npx/876480043fc67df8/node_modules/check-tests/bin/check.js:89:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
##[error]Bash exited with code '1'.
Finishing: Upload Playwright tests

```

**Comment by bheemreddy181** [comment]
i assume folder naming has a problem

**Comment by olexandr13** [comment]
Will be fixed with https://github.com/testomatio/check-tests/issues/132

**Comment by olexandr13** [comment]
fixed in https://github.com/testomatio/check-tests/pull/138
appears in the next release
